project:
  type: website

website:
  title: "Biodiversity Futures Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: wiki.qmd
        text: Best Practices
      - href: outputs.qmd
        text: Outputs
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Biodiversity-Futures-Lab/Biodiversity-Futures-Lab.github.io
          - text: Report an Issue
            href:  https://github.com/Biodiversity-Futures-Lab/Biodiversity-Futures-Lab.github.io/issues

format:
  html:
    allow-html: true
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
